### ISSUE TITLE
png images can be optimized using optipng without any detail loss.

### ISSUE THREAD

**Issue by Jieiku** [simbleau/simbleau.github.io#10]
png images can be optimized using optipng without any detail loss.

Place your png files in a directory then do this from that directory:

`optipng -o7 -zm1-9 -strip all *.png`

PS: I noticed your banner is an SVG file and the text is embedded right in, that's a great idea, I will be doing the same thing!

The result is png files less than half the size:

![2022-05-26_22-58-25](https://user-images.githubusercontent.com/106644/170639420-153a05fe-471d-46f4-aaec-f5f786503d3a.png)

**Comment by simbleau** [comment]
Thanks! I'll get around to this :)

**Comment by Jieiku** [comment]
I just found oxipng today, its even faster and compress just a tad better (less than 1% improvement in size but exponentially faster)

`oxipng -o max --strip all *.png`

**Comment by simbleau** [comment]
Fixed per 83e1bcb, thanks!
